const express = require('express');
const JWT = require('jsonwebtoken');
const JWTStrategy = require('passport-jwt').Strategy;
var localStrategy = require('passport-local');
var passport = require('passport');
var {Doctor} = require('../../models/DoctorSchema');
var {Patient} = require('../../models/PatientSchema');
const router = express.Router();
//passport local strategy configuration